apiVersion: v1
kind: Service
metadata:
  name: product-ms-service
spec:
  selector:
    app: product-ms
  ports:
    - protocol: TCP
      port: 80        # Service port inside the cluster
      targetPort: 8081 # Port inside the container
  type: ClusterIP     # Internal service, not exposed to the internet
